[general]
; name member server jabber
name_sensor = R2
; password client name_sensor jabber
passxmpp = 'xxx'
; name access point
ssid = POINT
; password Wi-Fi
password = 
; ntp server name default 0.ru.pool.ntp.org
ntp_server = ntp.localnet.lan
; time zone default SAMT-4
;tz_zone_info = SAMT-4
; name server jabber  
server = jaber.example.com
; receiver of messages from the sensor name_sensor
recipient = you@jabber.com
; port server default 5222
;port = 5222
; wake time to save battery in minutes default 4
;sleep = 4
; resource identifier default esp32-aaa
;resource = chat
; alarm zone number send message default 5
; only: 1,2,3,4,5,6,7
; number zone, min dist cm, max dist cm, name
; 1,           0,           50,          "Очень близко"
; 2,           51,          150,         "Близко"
; 3,           151,         200,         "Рядом"
; 4,           201,         250,         "Недалеко"
; 5,           251,         300,         "Далековато"
; 6,           301,         400,         "Далеко"
; 7,           401,         801,         "Очень далеко"
;alarm_zone = 5
