[general]
; name member server jabber
name_sensor = R2
; password client name_sensor jabber
passxmpp = 'xxx'
; name access point
ssid = POINT
; password Wi-Fi
password = 
; ntp server name
ntp_server = ntp.localnet.lan
; time zone
tz_zone_info = SAMT-4
; name server jabber  
server = jaber.example.com
; receiver of messages from the sensor name_sensor
recipient = you@jabber.com
; port server
port = 5222
; wake time to save battery in minutes
sleep = 4

